language: node_js

os:
  - linux
  # TODO(REENABLE): Disable **slow** windows for now.
  # - windows

node_js:
  # Include 8.10.0 for npm < 5.7.0 without `npm ci` command.
  - "8.10.0"
  - "8"
  - "10"
  - "11"

branches:
  only:
    - master

install:
  # Fail if lockfile outdated.
  # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - yarn install --frozen-lockfile

script:
  - yarn --version
  - yarn run check
  - yarn benchmark:build
  - "node -e \"process.exit(process.platform === 'win32' ? 0 : 1);\" || yarn check:git-dirty"
  - yarn benchmark:install
  - yarn benchmark:lint
  # Get cache corruption on windows in parallel.
  - yarn benchmark
  - yarn benchmark:test

# Enable both yarn and npm caches.
cache:
  - yarn
  - npm