environment:
  matrix:
    - nodejs_version: "8.10.0"
    - nodejs_version: "8"
    - nodejs_version: "10"
    - nodejs_version: "11"

install:
  - ps: Install-Product node $env:nodejs_version
  # Get a more modern yarn. And cross-env for windows exec ease.
  - npm install --global cross-env yarn@latest
  # Fail if lockfile outdated.
  # https://yarnpkg.com/lang/en/docs/cli/install/#toc-yarn-install-frozen-lockfile
  - yarn install --frozen-lockfile

test_script:
  - yarn --version
  - yarn run check
  - yarn benchmark:build
  - yarn benchmark:install
  - yarn benchmark:lint
  - cross-env TEST_PARALLEL=true yarn benchmark
  - yarn benchmark:test

# Don't actually build.
build: off

matrix:
  fast_finish: true

cache:
 - node_modules
 - "%LOCALAPPDATA%/Yarn"
